apiVersion: template.openshift.io/v1
kind: Template
parameters:
- description: The namespace containing ProwJobs.
  name: NAMESPACE
  value: ci
- description: The namespace containing the poller.
  name: POLL_NAMESPACE
  value: periscope
- description: The name of the component.
  name: NAME
  value: poll
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${NAME}"
    namespace: "${POLL_NAMESPACE}"
- kind: ClusterRole
  apiVersion: v1 # rbac.authorization.k8s.io/v1beta1
  metadata:
    name: "${NAME}"
  rules:
    - apiGroups:
        - "prow.k8s.io"
      resources:
        - prowjobs
      verbs:
        - get
        - list
- kind: ClusterRoleBinding
  apiVersion: v1 # rbac.authorization.k8s.io/v1beta1
  metadata:
    name: "${NAME}"
  roleRef:
    apiGroup: "" # rbac.authorization.k8s.io
    kind: ClusterRole
    name: "${NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${NAME}"
    namespace: "${POLL_NAMESPACE}"
